// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAI-z8HMb8IDfsN_Cei_qp_K0FamKSPuMg',
    appId: '1:853280509993:web:c4b5c58470edce25ab8c38',
    messagingSenderId: '853280509993',
    projectId: 'medqr-3e1ce',
    authDomain: 'medqr-3e1ce.firebaseapp.com',
    storageBucket: 'medqr-3e1ce.appspot.com',
    measurementId: 'G-YSFNRL8TBQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApsJyDK-ssUQ90SAljOXOM2QP0SXAagfA',
    appId: '1:853280509993:android:96f3d367e428e4baab8c38',
    messagingSenderId: '853280509993',
    projectId: 'medqr-3e1ce',
    storageBucket: 'medqr-3e1ce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnPFG7mSGnkSzbzx5NrcH80x9N9UZbVCo',
    appId: '1:853280509993:ios:18f938d4d625fc90ab8c38',
    messagingSenderId: '853280509993',
    projectId: 'medqr-3e1ce',
    storageBucket: 'medqr-3e1ce.appspot.com',
    iosBundleId: 'com.example.aapDevProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnPFG7mSGnkSzbzx5NrcH80x9N9UZbVCo',
    appId: '1:853280509993:ios:af39e8ac9dbba6dfab8c38',
    messagingSenderId: '853280509993',
    projectId: 'medqr-3e1ce',
    storageBucket: 'medqr-3e1ce.appspot.com',
    iosBundleId: 'com.example.aapDevProject.RunnerTests',
  );
}
